// Todo texto de erro que o usuário vê sai daqui. Nunca repassar a mensagem crua do Supabase ou do banco.
export const mensagens = {
  entrar: {
    camposVazios: "Preencha o e-mail e a senha.",
    credenciaisInvalidas: "E-mail ou senha incorretos. Confira e tente de novo.",
    muitasTentativas: "Muitas tentativas seguidas. Espere alguns minutos e tente de novo.",
    indisponivel: "Não foi possível entrar agora. Tente de novo em alguns minutos.",
  },
  posicao: {
    indisponivel: "Não foi possível carregar as obras agora. Recarregue a página em alguns minutos.",
    semObras: "Nenhuma obra liberada para o seu perfil. Peça acesso ao administrador da construtora.",
  },
  obra: {
    naoEncontrada: "Obra não encontrada ou sem permissão.",
    indisponivel: "Não foi possível carregar esta obra agora. Recarregue a página em alguns minutos.",
    semMovimento: "Esta obra ainda não tem entradas nem saídas nos 36 meses mostrados no gráfico.",
  },
  alertas: {
    indisponivel: "Não foi possível carregar os alertas agora. Recarregue a página em alguns minutos.",
    nenhum: "Nenhum alerta com os dados da última carga.",
  },
  estoque: {
    indisponivel: "Não foi possível carregar o estoque desta obra agora. Recarregue a página em alguns minutos.",
    semUnidades: "Esta obra ainda não tem unidades carregadas. Elas aparecem depois da próxima carga de dados.",
    semVendas: "Esta obra ainda não tem contratos de venda carregados.",
  },
  simulacao: {
    indisponivel: "Não foi possível calcular a simulação agora. Recarregue a página em alguns minutos.",
    semEstoque: "Esta obra não tem unidade em estoque com preço de tabela, então não há venda para simular.",
  },
  unidades: {
    indisponivel: "Não foi possível carregar o mapa de unidades agora. Recarregue a página em alguns minutos.",
    obraNaoEncontrada: "Obra não encontrada ou sem permissão para o seu perfil.",
    semUnidades: "Esta obra ainda não tem unidades carregadas. Elas aparecem depois da próxima carga de dados.",
  },
  assistente: {
    indisponivel: "Não foi possível responder agora. Tente de novo em alguns minutos.",
    perguntaDesconhecida: "Essa pergunta não está na lista. Escolha uma das perguntas abaixo.",
    semUsuario: "Sua sessão expirou. Entre de novo para continuar.",
    semAcesso: "Seu usuário ainda não está ligado a uma construtora. Peça acesso ao administrador.",
    semSegundoFator: "Confirme o código do aplicativo autenticador para usar o assistente. Recarregue a página para continuar.",
    falhaRede: "Não foi possível falar com o servidor. Confira a conexão e tente de novo.",
    perguntaInvalida: "Escreva a pergunta com 3 a 500 caracteres.",
    limite: "Limite de 30 perguntas por hora atingido. Tente de novo mais tarde ou use as perguntas prontas.",
    teto: "A construtora atingiu o limite diário de uso do assistente. As perguntas prontas continuam disponíveis; o assistente volta amanhã.",
    consultaInsegura: "Não consegui montar uma consulta segura para essa pergunta. Tente perguntar de outro jeito.",
    foraDoCatalogo:
      "Não encontrei nos dados do painel como responder a essa pergunta. Pergunte sobre caixa, recebimentos, pagamentos, vendas ou estoque das obras.",
    execucao: "Não consegui executar essa pergunta. Tente reformular.",
    semDados: "Não encontrei dados para essa pergunta nas obras liberadas para o seu perfil.",
    historicoIndisponivel: "Não foi possível carregar suas últimas perguntas agora. Recarregue a página em alguns minutos.",
    respostaSoTabela: "A resposta está na tabela abaixo, calculada direto dos dados do painel.",
  },
  carga: {
    semConferencia: "Atenção: não foi possível conferir a data da última carga. Recarregue a página em alguns minutos.",
    semCarga: "Atenção: nenhuma carga de dados foi concluída ainda. Os números aparecem depois da primeira carga.",
    atrasada: "Atenção: a carga de hoje não rodou.",
    numerosDe: "Os números são de",
    carregadaEm: "Dados carregados em",
    avisoDemo: "Dados da demo: valores gerados para demonstração, sem relação com uma construtora real.",
  },
  segundoFator: {
    codigoFormato: "Digite os seis dígitos que aparecem no aplicativo autenticador.",
    codigoInvalido: "Código incorreto ou vencido. Espere o aplicativo gerar um código novo e tente de novo.",
    muitasTentativas: "Muitas tentativas seguidas. Espere alguns minutos e tente de novo.",
    desligado: "O segundo fator ainda não está ligado neste ambiente. Avise o administrador da construtora.",
    semFator: "Nenhum aplicativo autenticador cadastrado. Cadastre um para continuar.",
    indisponivel: "Não foi possível concluir agora. Tente de novo em alguns minutos.",
    recomecar: "O cadastro não pôde ser concluído. Gere o código QR de novo e cadastre o aplicativo outra vez.",
    confirmarAntes: "Confirme o código do aplicativo já cadastrado antes de cadastrar outro.",
  },
  dre: {
    indisponivel: "Não foi possível carregar a DRE de viabilidade agora. Recarregue a página em alguns minutos.",
    semEstudo: "Esta obra ainda não tem estudo de viabilidade cadastrado.",
    semObras: "Nenhuma obra tem estudo de viabilidade cadastrado ainda.",
    restrita: "O seu perfil não abre a DRE de viabilidade. Peça ao diretor da construtora para liberar.",
    serieVazia: "A série começa no mês da primeira carga.",
    serieIndisponivel: "Não foi possível carregar a série mensal agora. Recarregue a página em alguns minutos.",
  },
  estudo: {
    gravado: "Estudo gravado. A DRE de viabilidade já usa a versão nova.",
    aliquotaGravada: "Alíquota gravada. A DRE de viabilidade já calcula os impostos com ela.",
    valorInvalido:
      "Confira os campos: valores só com números e vírgula para os centavos, sem sinal; alíquota de 0 a 20%; data de hoje ou anterior; descrição com até 120 caracteres.",
    semPermissao: "Só diretor e financeiro, com o segundo fator confirmado, gravam o estudo e a alíquota desta obra.",
    indisponivel: "Não foi possível gravar agora. Tente de novo em alguns minutos.",
    limite: "Esta obra já recebeu 20 versões do estudo hoje. Tente de novo amanhã.",
    semVersoes: "Nenhuma versão gravada ainda. A primeira gravação cria a versão 1.",
    semAliquota: "Nenhuma alíquota informada ainda. Sem ela, a DRE mostra os impostos realizados como zero.",
    avisoAliquota: "Alíquota informada pela construtora. O APO não apura imposto.",
  },
} as const;
